services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: dev-proudmoore-website-backend
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PROJECT_STATUS: ${PROJECT_STATUS}
      JWT_SECRET: ${JWT_SECRET}
      PROUDMOORE_ADMIN_PASSWORD: ${PROUDMOORE_ADMIN_PASSWORD}
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:8002/graphql'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 1s
      timeout: 2s
      retries: 5
      start_period: 2s
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: dev-proudmoore-website-frontend
    environment:
      VITE_PROJECT_STATUS: ${PROJECT_STATUS}
      VITE_FRONTEND_URL: ${FRONTEND_URL}
      VITE_FALLBACK_LOCALE: ${FALLBACK_LOCALE}
      VITE_DEFAULT_LOCALE: ${DEFAULT_LOCALE}
    volumes:
      - ./frontend/src/i18n:/app/src/i18n
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "5173:5173"
      - "7002:7002"
    command: ["npm", "run", "dev"]

  db:
    image: postgres
    container_name: dev-proudmoore-website-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
    - ./database:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 1s
      timeout: 2s
      retries: 5
      start_period: 2s

  redis:
    image: redis
    container_name: dev-proudmoore-website-redis

  adminer:
    image: adminer
    container_name: dev-proudmoore-website-adminer
    expose:
      - 8080

  apigateway:
    image: nginx
    container_name: dev-proudmoore-website-apigateway
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - backend
      - db